name: Deploy MultiDocker
on:
  push:
    branches:
      - main
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t viscarra97/react-test -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true viscarra97/react-test npm test
 
      - run: docker build -t viscarra97/multi-client ./client
      - run: docker build -t viscarra97/multi-nginx ./nginx
      - run: docker build -t viscarra97/multi-server ./server
      - run: docker build -t viscarra97/multi-worker ./worker
 
      - run: docker push viscarra97/multi-client
      - run: docker push viscarra97/multi-nginx
      - run: docker push viscarra97/multi-server
      - run: docker push viscarra97/multi-worker

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'
 
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v20
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: multi-docker
          environment_name: Multidocker-env
          existing_bucket_name: elasticbeanstalk-us-east-2-207101409492
          region: us-east-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip